sudo: required
dist: trusty
language: node_js
node_js:
  - '6.3.1'

addons:
apt:
  #sources:
  #  - google-chrome
  #packages:
  #  - google-chrome-stable
  #  - google-chrome-beta

before_install:
  #- export CHROME_BIN=chromium-browser
  #- export DISPLAY=:99.0
  #- sh -e /etc/init.d/xvfb start
  - cd public/

before_script:
- npm install -g angular-cli
- npm install -g karma
- npm install
- ng build
#- ng build -prod

#script: karma start config/karma.conf.js --single-run
script: ng test --watch false